### PR TITLE
Use ANDROID_HOME if set.

### PR DESCRIPTION
**Pull request by alexanderkjeldaas**

### CODE REVIEW

**Comment by angerman** [comment]
Sure why not looks good to me.

**Comment by alexanderkjeldaas** [comment]
not really tested.. 

I'm not sure what $ANDROID_NDK/sysroot should contain.
Also, could you turn on issues in this repo?

**Comment by angerman** [comment]
Issues should be available now.

**Comment by alexanderkjeldaas** [comment]
thanks!

**Pull request merged**
